### ISSUE TITLE
  raise KeyError(key) from err KeyError: 'emotion'

### ISSUE THREAD

**Issue by xiaotian02020** [omarsayed7/Deep-Emotion#13]
After I successfully run the command (python main.py -s setup  -d data), I got the corresponding photos and table. However, when I run the command (python main.py  -t train -d data), I still did not start the training. 

The error was as follows :   KeyError: 'emotion'
     Traceback (most recent call last):
     File "main.py", line 104, in <module>
     validation_dataset= Plain_Dataset(csv_file=validationcsv_file, img_dir = validation_img_dir, datatype = 'val', 
      transform = transformation)
      self.lables = self.csv_file['emotion']
      indexer = self.columns.get_loc(key)
      raise KeyError(key) from err
      KeyError: 'emotion'

How to solve this problem, thank you

**Comment by omarsayed7** [comment]
Hello, There were changes in kaggle dataset, so I updated the code to work with the new shape of the dataset 
https://github.com/omarsayed7/Deep-Emotion/commit/bccde6bc12d194af2dcdef579534806d81deeb86
