### ISSUE TITLE
Question about  the  code about model

### ISSUE THREAD

**Issue by yangqian-qian** [omarsayed7/Deep-Emotion#5]
The spatial transformation network proposed in this paper is applied to the last layer's feature maps, but it is applied to the input image in the code provided,  and  I used the fer2013 dataset to train the network, but I only got 55% accuracy, which is much lower than the data provided in the paper. Why? I hope you can tell me about it. Thank you very much!

**Comment by QingyangZhang** [comment]
> The spatial transformation network proposed in this paper is applied to the last layer's feature maps, but it is applied to the input image in the code provided, and I used the fer2013 dataset to train the network, but I only got 55% accuracy, which is much lower than the data provided in the paper. Why? I hope you can tell me about it. Thank you very much!

I got the same result ! The code is SHIT !

**Comment by hejingwen2019102936** [comment]
me too

**Comment by QingyangZhang** [comment]
There is no attention layers in this implement, it is just a simple CNN with six conv layers, even worser.
In other project, I got 66% acc in 23 epochs with my Xception-Net easily on FER2013 DB.
HOW DID THIS COMMIT GOT THESE STARS ?  UNBELIEABLE !

**Comment by yangqian-qian** [comment]
> 
> 
> There is no attention layers in this implement, it is just a simple CNN with six conv layers, even worser.
> In other project, I got 66% acc in 23 epochs with my Xception-Net easily on FER2013 DB.
> HOW DID THIS COMMIT GOT THESE STARS ? UNBELIEABLE !


well, this code has attention mechanism,  there is an stn function in deep_ emotion.py, which implements the attention mechanism on the spatial channel。

**Comment by omarsayed7** [comment]
> There is no attention layers in this implement, it is just a simple CNN with six conv layers, even worser.
> In other project, I got 66% acc in 23 epochs with my Xception-Net easily on FER2013 DB.
> HOW DID THIS COMMIT GOT THESE STARS ? UNBELIEABLE !

This code has "stn" function in deep_emotion.py, also feel free to modify the code and if you got better results you can pull request the modifications.
it's just practicing, not the official implementation of the paper, also it's open-source anyone can modify and contribute.

**Comment by nanhui69** [comment]
> implements

这个模型你最后用了么？
